/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAttribute: typeof import('./src/components/attributes/AddAttribute.vue')['default']
    AddCompany: typeof import('./src/components/companys/addCompany.vue')['default']
    AddItem: typeof import('./src/components/addItem.vue')['default']
    AddUser: typeof import('./src/components/cashboxs/addUser.vue')['default']
    AdvancedSearch: typeof import('./src/components/AdvancedSearch.vue')['default']
    Attributes: typeof import('./src/components/attributes/attributes.vue')['default']
    AttributeValues: typeof import('./src/components/attributeValues/attributeValues.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    CashBoxSwitcher: typeof import('./src/components/cashboxs/CashBoxSwitcher.vue')['default']
    Categorys: typeof import('./src/components/Category/categorys.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    copy: typeof import('./src/components/ContextMenu copy.vue')['default']
    DataTable: typeof import('./src/components/cashboxs/DataTable.vue')['default']
    DatePicker: typeof import('./src/components/datePicker.vue')['default']
    DeletedItem: typeof import('./src/components/DeletedItem.vue')['default']
    EditUserRolse: typeof import('./src/components/cashboxs/editUserRolse.vue')['default']
    Element: typeof import('./src/components/Element.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    Products: typeof import('./src/components/brands/products.vue')['default']
    ProductVariantAttributes: typeof import('./src/components/productVariantAttributes/productVariantAttributes.vue')['default']
    ProductVariants: typeof import('./src/components/productVariants/productVariants.vue')['default']
    RoleDetails: typeof import('./src/components/roles/RoleDetails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stock: typeof import('./src/components/stock/stock.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    TransactionDialog: typeof import('./src/components/cashboxs/transfer/TransactionDialog.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
    Warehouses: typeof import('./src/components/warehouses/warehouses.vue')['default']
  }
}
